export const properties = [
  {
    name: "Träd Kojjan",
    streetAddress: "Storgatan 1",
    postalAddress: "511 56 Kinna",
    technicalAlarms: 0,
    operationalAlarms: 1,
    safetyAlarms: 2,
    newAlarms: 5,
    latitude: 57.5074,
    longitude: 12.6921,
  },
  {
    name: "Ankeborg",
    streetAddress: "Kungsgatan 12",
    postalAddress: "503 34 Borås",
    technicalAlarms: 4,
    operationalAlarms: 2,
    safetyAlarms: 2,
    newAlarms: 0,
    latitude: 57.7211,
    longitude: 12.7404,
  },
  {
    name: "Fastighet C",
    streetAddress: "Sveavägen 33",
    postalAddress: "515 34 Viskafors",
    technicalAlarms: 3,
    operationalAlarms: 0,
    safetyAlarms: 1,
    newAlarms: 0,
    latitude: 57.6356,
    longitude: 12.7563,
  },
  {
    name: "Fastighet D",
    streetAddress: "Vasagatan 5",
    postalAddress: "512 50 Svenljunga",
    technicalAlarms: 5,
    operationalAlarms: 3,
    safetyAlarms: 0,
    newAlarms: 1,
    latitude: 57.4957,
    longitude: 13.1128,
  },
  {
    name: "Fastighet E",
    streetAddress: "Drottninggatan 22",
    postalAddress: "517 33 Bollebygd",
    technicalAlarms: 0,
    operationalAlarms: 0,
    safetyAlarms: 0,
    newAlarms: 0,
    latitude: 57.6679,
    longitude: 12.5735,
  },
  {
    name: "Fastighet F",
    streetAddress: "Linnégatan 8",
    postalAddress: "516 33 Dalsjöfors",
    technicalAlarms: 1,
    operationalAlarms: 2,
    safetyAlarms: 2,
    newAlarms: 3,
    latitude: 57.6219,
    longitude: 13.0681,
  },
  {
    name: "Fastighet G",
    streetAddress: "Hamngatan 14",
    postalAddress: "504 50 Borås",
    technicalAlarms: 4,
    operationalAlarms: 3,
    safetyAlarms: 2,
    newAlarms: 0,
    latitude: 57.7221,
    longitude: 12.9389,
  },
  {
    name: "Fastighet H",
    streetAddress: "Kungsgatan 42",
    postalAddress: "511 96 Öxabäck",
    technicalAlarms: 2,
    operationalAlarms: 1,
    safetyAlarms: 1,
    newAlarms: 0,
    latitude: 57.3912,
    longitude: 12.7995,
  },
  {
    name: "Fastighet I",
    streetAddress: "Östra Långgatan 7",
    postalAddress: "512 60 Överlida",
    technicalAlarms: 0,
    operationalAlarms: 4,
    safetyAlarms: 0,
    newAlarms: 3,
    latitude: 57.3489,
    longitude: 13.0842,
  },
];

export const alarms = [
  {
    name: "Technical Alarms",
    symbol: "./src/assets/technical.svg",
    options: ["Communication Failure", "Sensor/Sum Alarms"],
  },
  {
    name: "Operational Alarms",
    symbol: "src/assets/Operational.svg",
    options: ["Zone Alarms", "Manual Operations"],
  },
  {
    name: "Safety Alarms",
    symbol: "src/assets/Saftey.svg",
    options: ["Fire Alarms"],
  },
  {
    name: "Device Alarms",
    symbol: "src/assets/device.svg",
    options: ["Heating Alarms", "Ventilation Alarms", "Cooling Alarms"],
  },
];
