export const properties = [
  {
    name: "Träd Kojjan",
    streetAddress: "Storgatan 1",
    postalAddress: "123 45 Stockholm",
    technicalAlarms: 0,
    operationalAlarms: 1,
    safetyAlarms: 2,
    newAlarms: 5,
  },
  {
    name: "Ankeborg",
    streetAddress: "Kungsgatan 12",
    postalAddress: "456 78 Göteborg",
    technicalAlarms: 4,
    operationalAlarms: 2,
    safetyAlarms: 2,
    newAlarms: 0,
  },
  {
    name: "Fastighet C",
    streetAddress: "Sveavägen 33",
    postalAddress: "987 65 Malmö",
    technicalAlarms: 3,
    operationalAlarms: 0,
    safetyAlarms: 1,
    newAlarms: 0,
  },
  {
    name: "Fastighet D",
    streetAddress: "Vasagatan 5",
    postalAddress: "543 21 Uppsala",
    technicalAlarms: 5,
    operationalAlarms: 3,
    safetyAlarms: 0,
    newAlarms: 1,
  },
  {
    name: "Fastighet E",
    streetAddress: "Drottninggatan 22",
    postalAddress: "789 12 Helsingborg",
    technicalAlarms: 0,
    operationalAlarms: 0,
    safetyAlarms: 0,
    newAlarms: 0,
  },
  {
    name: "Fastighet F",
    streetAddress: "Linnégatan 8",
    postalAddress: "321 54 Göteborg",
    technicalAlarms: 3,
    operationalAlarms: 2,
    safetyAlarms: 2,
    newAlarms: 3,
  },
  {
    name: "Fastighet G",
    streetAddress: "Hamngatan 14",
    postalAddress: "654 32 Linköping",
    technicalAlarms: 4,
    operationalAlarms: 3,
    safetyAlarms: 2,
    newAlarms: 0,
  },
  {
    name: "Fastighet H",
    streetAddress: "Kungsgatan 42",
    postalAddress: "852 14 Västerås",
    technicalAlarms: 2,
    operationalAlarms: 1,
    safetyAlarms: 1,
    newAlarms: 0,
  },
  {
    name: "Fastighet I",
    streetAddress: "Östra Långgatan 7",
    postalAddress: "963 85 Norrköping",
    technicalAlarms: 0,
    operationalAlarms: 4,
    safetyAlarms: 0,
    newAlarms: 3,
  },
  {
    name: "Fastighet J",
    streetAddress: "Centralvägen 9",
    postalAddress: "147 25 Sundsvall",
    technicalAlarms: 2,
    operationalAlarms: 2,
    safetyAlarms: 1,
    newAlarms: 0,
  },
];
